Catch SameFileError explicitly in _copytree
If not, it is caught as a shutil.Error for which it is assumed to be a
recursive error, resulting in splitting of the error string as
```
shutil.Error: ['<', 'D', 'i', 'r', 'E', 'n', 't', 'r', 'y', ' ', ...,
               's', 'a', 'm', 'e', ' ', 'f', 'i', 'l', 'e']
```